POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Susans Story",
  "author": "Susan Ofcourse",
  "url": "testURL.com",
  "likes": 33
}
###
GET http://localhost:3001/api/blogs
Content-Type: application/json